// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4DRq_t_Hb-_d_DTpNiHwvBHvawo6m7rg',
    appId: '1:477617589429:web:a2050fe53a0a5f5e18c2fc',
    messagingSenderId: '477617589429',
    projectId: 'purebloodflutter',
    authDomain: 'purebloodflutter.firebaseapp.com',
    storageBucket: 'purebloodflutter.appspot.com',
    measurementId: 'G-FWNLTGGQBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGBkxnwsYxupdJwzBYrgmSlFuslsLdL0',
    appId: '1:477617589429:android:fab3f677bfe32f3918c2fc',
    messagingSenderId: '477617589429',
    projectId: 'purebloodflutter',
    storageBucket: 'purebloodflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0JBiIksUpbuGEVvtM2zjW_f8Li7ojF8',
    appId: '1:477617589429:ios:579413fa3696b4f318c2fc',
    messagingSenderId: '477617589429',
    projectId: 'purebloodflutter',
    storageBucket: 'purebloodflutter.appspot.com',
    iosClientId: '477617589429-36utkefef3nn8e07i0pe649q3520uq7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureBlood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0JBiIksUpbuGEVvtM2zjW_f8Li7ojF8',
    appId: '1:477617589429:ios:579413fa3696b4f318c2fc',
    messagingSenderId: '477617589429',
    projectId: 'purebloodflutter',
    storageBucket: 'purebloodflutter.appspot.com',
    iosClientId: '477617589429-36utkefef3nn8e07i0pe649q3520uq7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.pureBlood',
  );
}
